import { SignInButton, SignedIn, SignedOut, UserButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  return (
    <>
      <Head>
        <title>Blobodoro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Blobodoro
          </h1>
          <div className="container h-96 w-96">
            <svg
              id="Layer_1"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 387.01 337.87"
            >
              <path
                id="Body"
                d="m153.08,66.23c-12.43,1.98-22.59,4.59-29.74,6.69-47.39,17.19-167.36,151.73-103.56,227.75,4.65,4.77,11.8,11.29,21.79,17.58,31.42,19.78,59.07,16.97,146.52,18.06,0,0,104.36,1.3,148.97-9.22,28.32-6.68,35.9-15.14,38.25-17.93,13.51-16.02,10.79-37.89,7.59-60.91-4.84-34.81-17.66-59.67-28.85-80.91,0,0-18.15-34.62-45.43-63.51-10.71-11.34-21.8-18.95-21.8-18.95-2.65-1.85-4.93-3.23-6.85-4.38-45.47-27.2-106.39-17.53-126.9-14.26Z"
                style={{
                  fill: "#f9c7d9",
                  stroke: "#d9527b",
                  strokeMiterlimit: 10,
                  strokeWidth: 3
                }}
              />
              <g id="Right_Eye">
                <path
                  d="m311.28,245.32c2.09,18.77-13.66,20.57-15.85,1.81-2.09-18.77,13.66-20.57,15.85-1.81Z"
                  style={{ fill: "#0c0b0d" }}
                />
                <path
                  d="m304.51,238.83c.05,4.12-5.61,4.12-5.55,0-.05-4.12,5.61-4.12,5.55,0Z"
                  style={{ fill: "#fff", stroke: "#012a25", strokeMiterlimit: 10 }}
                />
              </g>
              <g id="Left_Eye">
                <path
                  d="m96.23,250.11c-2.18,17.82-18.29,15.91-16.23-1.93,2.18-17.82,18.29-15.91,16.23,1.93Z"
                  style={{ fill: "#0c0b0d" }}
                />
                <path
                  d="m91.96,242.1c.05,3.94-5.55,3.94-5.49,0-.05-3.94,5.55-3.94,5.49,0Z"
                  style={{ fill: "#fff", stroke: "#012a25", strokeMiterlimit: 10 }}
                />
              </g>
              <g id="Nose">
                <path
                  d="m238.33,217.1c-11.58,82.79-98.91,71.81-89.65-11.26,11.58-82.79,98.91-71.81,89.65,11.26Z"
                  style={{ fill: "#f9c7d9" }}
                />
                <path
                  d="m148.05,230.47c1.51,10.51,4.75,21.14,11.1,29.78,4.89,6.66,11.53,11.94,19.47,14.44,7.39,2.33,15.46,2.05,22.79-.37,8.11-2.68,15.29-7.76,20.96-14.11,6.81-7.62,11.52-16.93,14.34-26.72.4-1.38.75-2.76,1.08-4.15.44-1.88-2.45-2.68-2.89-.8-2.26,9.67-6.24,19.06-12.42,26.9-5.06,6.42-11.58,11.87-19.19,15-6.66,2.74-14.09,3.68-21.16,2.09-7.45-1.68-13.91-5.98-18.8-11.79-6.33-7.51-9.8-17.1-11.64-26.64-.28-1.47-.53-2.95-.74-4.44-.27-1.9-3.16-1.09-2.89.8h0Z"
                  style={{ fill: "#d05179" }}
                />
              </g>
              <g id="Hair">
                <path
                  d="m289.76,77.28c-2.15,2.7-15.73,19.19-39.67,21.07-28.77,2.26-46.76-18.6-48.22-20.36-.18,15.14-8.96,28.02-21.59,32.25-9.91,3.32-18.99.26-22.17-.98,10.59-1.41,19.43-7.96,22.84-17.04,3.67-9.77-.48-18.41-1.39-20.19-14.03,19.43-34.11,29.61-50.56,25.41-3.48-.89-8.29-2.8-13.32-7.29,6.75-1.2,15.69-3.5,25.41-8.14,7.4-3.53,13.31-7.49,17.8-10.97-24.97-6.48-78.55,14.8-76.77-31.75,32.45,43.34,64.63-8.51,97.2,7.26,19.26,3.31,43.92,5.78,72.43,4.3,21.5-1.11,40.37-4.22,56-7.79-8.72,16.23-20.04,22.11-24.9,24.19-14.41,6.17-30.66,4-46.03,1.95-9.97-1.33-16.31-3.2-16.43-2.57-.12.62,13.93,7.62,32.01,10.21,23.07,3.31,36.52-2.88,37.35.42Z"
                  style={{
                    fill: "#3ea47c",
                    stroke: "#2d4a21",
                    strokeMiterlimit: 10,
                    strokeWidth: 2
                  }}
                />
                <path
                  d="m173.9,2.94l13.21-1.9,11.38,5.53c-4.35,15.7-4.45,32.98-7.23,49.02-.78,3.53-4.11,5.76-7.29,5.23-2.65-.44-4.81-2.72-5.21-5.63-1.62-17.42-3.24-34.83-4.85-52.25Z"
                  style={{
                    fill: "#0d6b37",
                    stroke: "#1c4a24",
                    strokeMiterlimit: 10,
                    strokeWidth: 2
                  }}
                />
              </g>
            </svg>
          </div>
          <div>
            <SignedIn>
              {/* Mount the UserButton component */}
              <UserButton />
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton />
            </SignedOut>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
